import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Archivo } from "next/font/google";

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`$ ${archivo.variable} antialiased relative `}>
        {children}
      </body>
    </html>
  );
}
